const express = require('express');
const productionController = require('../controller/production.controller');

const router = express.Router();
router.post('/startProduction', productionController.startProduction);
router.post('/getProductions', productionController.getProductions);
router.post('/getProductionById', productionController.getProductionById);
router.post('/bulkGetProductionsByIds', productionController.bulkGetProductionsByIds);
router.post('/issueRawMaterial', productionController.issueRawMaterial);
router.post('/updateProcess', productionController.updateProcess);
router.post('/updateCost', productionController.updateCost);
router.post('/updateScrapLogs', productionController.updateScrapLogs);
router.post('/saveFinishedGoods', productionController.saveFinishedGoods);
router.post('/updateProductionStatus', productionController.updateProductionStatus);
router.post('/saveProduction', productionController.saveProduction);
router.post('/materialPlanning', productionController.materialPlanning);
router.post('/bomBasedMaterialPlanning', productionController.bomBasedMaterialPlanning);
router.post('/getProductionsByCompanyId', productionController.getProductionsByCompanyId);
router.post('/productionBasedMaterialPlanning', productionController.productionBasedMaterialPlanning);
router.post('/updateTable', productionController.updateTable);
router.post('/removeRows', productionController.removeRows);
router.post('/viewProductionHistory', productionController.viewProductionHistory);
router.post('/returnRawMaterial', productionController.returnRawMaterial);
router.post('/startBulkProduction', productionController.startBulkProduction);
router.post('/getBulkProductions', productionController.getBulkProductions);
router.post('/remainingProduction', productionController.remainingProduction);
router.post('/discardProduction', productionController.discardProduction);
router.post('/bulkIssue', productionController.bulkIssue);
router.post('/updateStartDate', productionController.updateStartDate);
router.post('/minStockMaterialPlanning', productionController.minStockMaterialPlanning);

module.exports = router;